---
- name: CLI Playbook
  hosts: wlc
  connection: network_cli
  gather_facts: false

  tasks:

    - name: "Get Max APs supported with CLI command"
      cisco.ios.ios_command:
        commands: "show wireless summary | include Max APs"
      register: result

    - name: "View result"
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
