all:
  children:
    wlc:
      hosts:
        192.168.10.9:
        192.168.10.30:
    switch:
      hosts:
        192.168.10.2:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_ssh_pass: ChangeMe2024!
    ansible_password: ChangeMe2024!
    ansible_user: devnet-adm
    ansible_host_key_checking: False
