wlc:
  hosts:
    192.168.10.9:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_ssh_pass: ChangeMe2024!
    ansible_password: ChangeMe2024!
    ansible_user: devnet-adm
    ansible_host_key_checking: False
    policy_profiles: 
      - name: test1
        vlan: 11
      - name: test2
        vlan: 12
      - name: test3
        vlan: 13
