{
 "title": "Cloud AP example dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "APName",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"host\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "AP Info: $APName",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_info",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IP" ], "type": "alias" }
      ],
      [
       { "params": [ "mac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Eth MAC" ], "type": "alias" }
      ],
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "ext_ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ext IP" ], "type": "alias" }
      ],
      [
       { "params": [ "mount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Mount" ], "type": "alias" }
      ],
      [
       { "params": [ "power_src" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power src" ], "type": "alias" }
      ],
      [
       { "params": [ "radio_mac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Radio MAC" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$APName$/" }
     ]
    }
   ]
  },
  {
   "title": "Channel history 2.4GHz",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "channel_history",
     "select": [
      [
       { "params": [ "2.4GHz Channel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Channel" ], "type": "alias" }
      ],
      [
       { "params": [ "2.4GHz Bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ch width" ], "type": "alias" }
      ],
      [
       { "params": [ "2.4GHz TxPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TxPower" ], "type": "alias" }
      ],
      [
       { "params": [ "2.4GHz #Clients" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "#Clients" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$APName$/" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Channel Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ch_utilization",
     "select": [
      [
       { "params": [ "2.4GHz Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CU%" ], "type": "alias" }
      ],
      [
       { "params": [ "2.4GHz Wi-Fi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Wi-Fi CU%" ], "type": "alias" }
      ],
      [
       { "params": [ "2.4GHz non-Wi-Fi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Non-Wi-Fi CU%" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$APName$/" }
     ]
    }
   ]
  },
  {
   "title": "Channel history 5GHz",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "channel_history",
     "select": [
      [
       { "params": [ "5GHz Channel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Channel" ], "type": "alias" }
      ],
      [
       { "params": [ "5GHz Bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ch width" ], "type": "alias" }
      ],
      [
       { "params": [ "5GHz TxPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TxPower" ], "type": "alias" }
      ],
      [
       { "params": [ "5GHz #Clients" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "#Clients" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$APName$/" }
     ]
    }
   ]
  },
  {
   "title": "5GHz Channel Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ch_utilization",
     "select": [
      [
       { "params": [ "5GHz Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CU%" ], "type": "alias" }
      ],
      [
       { "params": [ "5GHz Wi-Fi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Wi-Fi CU%" ], "type": "alias" }
      ],
      [
       { "params": [ "5GHz non-Wi-Fi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Non-Wi-Fi CU%" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$APName$/" }
     ]
    }
   ]
  },
  {
   "title": "6GHz Channel Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ch_utilization",
     "select": [
      [
       { "params": [ "6GHz Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CU%" ], "type": "alias" }
      ],
      [
       { "params": [ "6GHz Wi-Fi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Wi-Fi CU%" ], "type": "alias" }
      ],
      [
       { "params": [ "6GHz non-Wi-Fi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Non-Wi-Fi CU%" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$APName$/" }
     ]
    }
   ]
  }
 ]
}