---
all:
  children:
    wlc-iosxe:
      hosts:
        192.168.10.9:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_ssh_pass: {PASSWORD}
    ansible_password: {PASSWORD}
    ansible_user: {USERNAME}
    ansible_host_key_checking: False
